version: '3.8'
services:
  web:
    build: .
    ports:
      - 5000:5000
    volumes:
      - ./src/Hotel:/app/src/Hotel
      - flask_migrations:/app/src/Hotel/migrations
    depends_on:
      - db
  
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: Hotel
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
  flask_migrations: